// Code generated by hertz generator.

package main

import (
	"fmt"
	"os"

	"xquant/cmd"
)

func main() {
	rootCmd := cmd.GlobalFlags()
	if err := rootCmd.Execute(); err != nil {
		_, err := fmt.Fprintf(os.Stderr, "root cmd execute error:%v", err)
		if err != nil {
			return
		}
		os.Exit(1)
	}
}
