// Code generated by hertz generator.

package main

import (
	"fmt"
	"os"
)

func main() {
	rootCmd.AddCommand(infoMetricsSeverCmd)
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "root cmd execute error:%v", err)
		os.Exit(1)
	}
}
