// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_api_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50101,
		Name:          "api.raw_body",
		Tag:           "bytes,50101,opt,name=raw_body",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50102,
		Name:          "api.query",
		Tag:           "bytes,50102,opt,name=query",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50103,
		Name:          "api.header",
		Tag:           "bytes,50103,opt,name=header",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50104,
		Name:          "api.cookie",
		Tag:           "bytes,50104,opt,name=cookie",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50105,
		Name:          "api.body",
		Tag:           "bytes,50105,opt,name=body",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50106,
		Name:          "api.path",
		Tag:           "bytes,50106,opt,name=path",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50107,
		Name:          "api.vd",
		Tag:           "bytes,50107,opt,name=vd",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50108,
		Name:          "api.form",
		Tag:           "bytes,50108,opt,name=form",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         51001,
		Name:          "api.go_tag",
		Tag:           "bytes,51001,opt,name=go_tag",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50109,
		Name:          "api.js_conv",
		Tag:           "bytes,50109,opt,name=js_conv",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50201,
		Name:          "api.get",
		Tag:           "bytes,50201,opt,name=get",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50202,
		Name:          "api.post",
		Tag:           "bytes,50202,opt,name=post",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50203,
		Name:          "api.put",
		Tag:           "bytes,50203,opt,name=put",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50204,
		Name:          "api.delete",
		Tag:           "bytes,50204,opt,name=delete",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50205,
		Name:          "api.patch",
		Tag:           "bytes,50205,opt,name=patch",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50206,
		Name:          "api.options",
		Tag:           "bytes,50206,opt,name=options",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50207,
		Name:          "api.head",
		Tag:           "bytes,50207,opt,name=head",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50208,
		Name:          "api.any",
		Tag:           "bytes,50208,opt,name=any",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50301,
		Name:          "api.gen_path",
		Tag:           "bytes,50301,opt,name=gen_path",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50302,
		Name:          "api.api_version",
		Tag:           "bytes,50302,opt,name=api_version",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50303,
		Name:          "api.tag",
		Tag:           "bytes,50303,opt,name=tag",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50304,
		Name:          "api.name",
		Tag:           "bytes,50304,opt,name=name",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50305,
		Name:          "api.api_level",
		Tag:           "bytes,50305,opt,name=api_level",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50306,
		Name:          "api.serializer",
		Tag:           "bytes,50306,opt,name=serializer",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50307,
		Name:          "api.param",
		Tag:           "bytes,50307,opt,name=param",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50308,
		Name:          "api.baseurl",
		Tag:           "bytes,50308,opt,name=baseurl",
		Filename:      "api.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50401,
		Name:          "api.http_code",
		Tag:           "varint,50401,opt,name=http_code",
		Filename:      "api.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string raw_body = 50101;
	E_RawBody = &file_api_proto_extTypes[0]
	// optional string query = 50102;
	E_Query = &file_api_proto_extTypes[1]
	// optional string header = 50103;
	E_Header = &file_api_proto_extTypes[2]
	// optional string cookie = 50104;
	E_Cookie = &file_api_proto_extTypes[3]
	// optional string body = 50105;
	E_Body = &file_api_proto_extTypes[4]
	// optional string path = 50106;
	E_Path = &file_api_proto_extTypes[5]
	// optional string vd = 50107;
	E_Vd = &file_api_proto_extTypes[6]
	// optional string form = 50108;
	E_Form = &file_api_proto_extTypes[7]
	// optional string go_tag = 51001;
	E_GoTag = &file_api_proto_extTypes[8]
	// optional string js_conv = 50109;
	E_JsConv = &file_api_proto_extTypes[9]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string get = 50201;
	E_Get = &file_api_proto_extTypes[10]
	// optional string post = 50202;
	E_Post = &file_api_proto_extTypes[11]
	// optional string put = 50203;
	E_Put = &file_api_proto_extTypes[12]
	// optional string delete = 50204;
	E_Delete = &file_api_proto_extTypes[13]
	// optional string patch = 50205;
	E_Patch = &file_api_proto_extTypes[14]
	// optional string options = 50206;
	E_Options = &file_api_proto_extTypes[15]
	// optional string head = 50207;
	E_Head = &file_api_proto_extTypes[16]
	// optional string any = 50208;
	E_Any = &file_api_proto_extTypes[17]
	// optional string gen_path = 50301;
	E_GenPath = &file_api_proto_extTypes[18]
	// optional string api_version = 50302;
	E_ApiVersion = &file_api_proto_extTypes[19]
	// optional string tag = 50303;
	E_Tag = &file_api_proto_extTypes[20]
	// optional string name = 50304;
	E_Name = &file_api_proto_extTypes[21]
	// optional string api_level = 50305;
	E_ApiLevel = &file_api_proto_extTypes[22]
	// optional string serializer = 50306;
	E_Serializer = &file_api_proto_extTypes[23]
	// optional string param = 50307;
	E_Param = &file_api_proto_extTypes[24]
	// optional string baseurl = 50308;
	E_Baseurl = &file_api_proto_extTypes[25]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional int32 http_code = 50401;
	E_HttpCode = &file_api_proto_extTypes[26]
)

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\x1a google/protobuf/descriptor.proto::\n" +
	"\braw_body\x12\x1d.google.protobuf.FieldOptions\x18\xb5\x87\x03 \x01(\tR\arawBody:5\n" +
	"\x05query\x12\x1d.google.protobuf.FieldOptions\x18\xb6\x87\x03 \x01(\tR\x05query:7\n" +
	"\x06header\x12\x1d.google.protobuf.FieldOptions\x18\xb7\x87\x03 \x01(\tR\x06header:7\n" +
	"\x06cookie\x12\x1d.google.protobuf.FieldOptions\x18\xb8\x87\x03 \x01(\tR\x06cookie:3\n" +
	"\x04body\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x87\x03 \x01(\tR\x04body:3\n" +
	"\x04path\x12\x1d.google.protobuf.FieldOptions\x18\xba\x87\x03 \x01(\tR\x04path:/\n" +
	"\x02vd\x12\x1d.google.protobuf.FieldOptions\x18\xbb\x87\x03 \x01(\tR\x02vd:3\n" +
	"\x04form\x12\x1d.google.protobuf.FieldOptions\x18\xbc\x87\x03 \x01(\tR\x04form:6\n" +
	"\x06go_tag\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x8e\x03 \x01(\tR\x05goTag:8\n" +
	"\ajs_conv\x12\x1d.google.protobuf.FieldOptions\x18\xbd\x87\x03 \x01(\tR\x06jsConv:2\n" +
	"\x03get\x12\x1e.google.protobuf.MethodOptions\x18\x99\x88\x03 \x01(\tR\x03get:4\n" +
	"\x04post\x12\x1e.google.protobuf.MethodOptions\x18\x9a\x88\x03 \x01(\tR\x04post:2\n" +
	"\x03put\x12\x1e.google.protobuf.MethodOptions\x18\x9b\x88\x03 \x01(\tR\x03put:8\n" +
	"\x06delete\x12\x1e.google.protobuf.MethodOptions\x18\x9c\x88\x03 \x01(\tR\x06delete:6\n" +
	"\x05patch\x12\x1e.google.protobuf.MethodOptions\x18\x9d\x88\x03 \x01(\tR\x05patch::\n" +
	"\aoptions\x12\x1e.google.protobuf.MethodOptions\x18\x9e\x88\x03 \x01(\tR\aoptions:4\n" +
	"\x04head\x12\x1e.google.protobuf.MethodOptions\x18\x9f\x88\x03 \x01(\tR\x04head:2\n" +
	"\x03any\x12\x1e.google.protobuf.MethodOptions\x18\xa0\x88\x03 \x01(\tR\x03any:;\n" +
	"\bgen_path\x12\x1e.google.protobuf.MethodOptions\x18\xfd\x88\x03 \x01(\tR\agenPath:A\n" +
	"\vapi_version\x12\x1e.google.protobuf.MethodOptions\x18\xfe\x88\x03 \x01(\tR\n" +
	"apiVersion:2\n" +
	"\x03tag\x12\x1e.google.protobuf.MethodOptions\x18\xff\x88\x03 \x01(\tR\x03tag:4\n" +
	"\x04name\x12\x1e.google.protobuf.MethodOptions\x18\x80\x89\x03 \x01(\tR\x04name:=\n" +
	"\tapi_level\x12\x1e.google.protobuf.MethodOptions\x18\x81\x89\x03 \x01(\tR\bapiLevel:@\n" +
	"\n" +
	"serializer\x12\x1e.google.protobuf.MethodOptions\x18\x82\x89\x03 \x01(\tR\n" +
	"serializer:6\n" +
	"\x05param\x12\x1e.google.protobuf.MethodOptions\x18\x83\x89\x03 \x01(\tR\x05param::\n" +
	"\abaseurl\x12\x1e.google.protobuf.MethodOptions\x18\x84\x89\x03 \x01(\tR\abaseurl:@\n" +
	"\thttp_code\x12!.google.protobuf.EnumValueOptions\x18\xe1\x89\x03 \x01(\x05R\bhttpCodeB\x06Z\x04/api"

var file_api_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),     // 0: google.protobuf.FieldOptions
	(*descriptorpb.MethodOptions)(nil),    // 1: google.protobuf.MethodOptions
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: api.raw_body:extendee -> google.protobuf.FieldOptions
	0,  // 1: api.query:extendee -> google.protobuf.FieldOptions
	0,  // 2: api.header:extendee -> google.protobuf.FieldOptions
	0,  // 3: api.cookie:extendee -> google.protobuf.FieldOptions
	0,  // 4: api.body:extendee -> google.protobuf.FieldOptions
	0,  // 5: api.path:extendee -> google.protobuf.FieldOptions
	0,  // 6: api.vd:extendee -> google.protobuf.FieldOptions
	0,  // 7: api.form:extendee -> google.protobuf.FieldOptions
	0,  // 8: api.go_tag:extendee -> google.protobuf.FieldOptions
	0,  // 9: api.js_conv:extendee -> google.protobuf.FieldOptions
	1,  // 10: api.get:extendee -> google.protobuf.MethodOptions
	1,  // 11: api.post:extendee -> google.protobuf.MethodOptions
	1,  // 12: api.put:extendee -> google.protobuf.MethodOptions
	1,  // 13: api.delete:extendee -> google.protobuf.MethodOptions
	1,  // 14: api.patch:extendee -> google.protobuf.MethodOptions
	1,  // 15: api.options:extendee -> google.protobuf.MethodOptions
	1,  // 16: api.head:extendee -> google.protobuf.MethodOptions
	1,  // 17: api.any:extendee -> google.protobuf.MethodOptions
	1,  // 18: api.gen_path:extendee -> google.protobuf.MethodOptions
	1,  // 19: api.api_version:extendee -> google.protobuf.MethodOptions
	1,  // 20: api.tag:extendee -> google.protobuf.MethodOptions
	1,  // 21: api.name:extendee -> google.protobuf.MethodOptions
	1,  // 22: api.api_level:extendee -> google.protobuf.MethodOptions
	1,  // 23: api.serializer:extendee -> google.protobuf.MethodOptions
	1,  // 24: api.param:extendee -> google.protobuf.MethodOptions
	1,  // 25: api.baseurl:extendee -> google.protobuf.MethodOptions
	2,  // 26: api.http_code:extendee -> google.protobuf.EnumValueOptions
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	0,  // [0:27] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 27,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		ExtensionInfos:    file_api_proto_extTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
