// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: backtest.proto

package backtest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int64                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`                 // 统计天数
	TopN          int64                  `protobuf:"varint,2,opt,name=topN,proto3" json:"topN,omitempty"`                 // 输出前排名数
	StrategyCode  uint64                 `protobuf:"varint,3,opt,name=strategyCode,proto3" json:"strategyCode,omitempty"` // 策略ID
	SecurityCode  string                 `protobuf:"bytes,4,opt,name=securityCode,proto3" json:"securityCode,omitempty"`  // 证券代码
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`                  // 日期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktestRequest) Reset() {
	*x = BacktestRequest{}
	mi := &file_backtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestRequest) ProtoMessage() {}

func (x *BacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestRequest.ProtoReflect.Descriptor instead.
func (*BacktestRequest) Descriptor() ([]byte, []int) {
	return file_backtest_proto_rawDescGZIP(), []int{0}
}

func (x *BacktestRequest) GetDays() int64 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *BacktestRequest) GetTopN() int64 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *BacktestRequest) GetStrategyCode() uint64 {
	if x != nil {
		return x.StrategyCode
	}
	return 0
}

func (x *BacktestRequest) GetSecurityCode() string {
	if x != nil {
		return x.SecurityCode
	}
	return ""
}

func (x *BacktestRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SingleSecurityCodeBacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyCode  uint64                 `protobuf:"varint,1,opt,name=strategyCode,proto3" json:"strategyCode,omitempty"` // 策略ID
	SecurityCode  string                 `protobuf:"bytes,2,opt,name=securityCode,proto3" json:"securityCode,omitempty"`  // 证券代码
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`                  // 日期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleSecurityCodeBacktestRequest) Reset() {
	*x = SingleSecurityCodeBacktestRequest{}
	mi := &file_backtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleSecurityCodeBacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleSecurityCodeBacktestRequest) ProtoMessage() {}

func (x *SingleSecurityCodeBacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleSecurityCodeBacktestRequest.ProtoReflect.Descriptor instead.
func (*SingleSecurityCodeBacktestRequest) Descriptor() ([]byte, []int) {
	return file_backtest_proto_rawDescGZIP(), []int{1}
}

func (x *SingleSecurityCodeBacktestRequest) GetStrategyCode() uint64 {
	if x != nil {
		return x.StrategyCode
	}
	return 0
}

func (x *SingleSecurityCodeBacktestRequest) GetSecurityCode() string {
	if x != nil {
		return x.SecurityCode
	}
	return ""
}

func (x *SingleSecurityCodeBacktestRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type StrategyBacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int64                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`                 // 统计天数
	TopN          int64                  `protobuf:"varint,2,opt,name=topN,proto3" json:"topN,omitempty"`                 // 输出前排名数
	StrategyCode  uint64                 `protobuf:"varint,3,opt,name=strategyCode,proto3" json:"strategyCode,omitempty"` // 策略ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyBacktestRequest) Reset() {
	*x = StrategyBacktestRequest{}
	mi := &file_backtest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyBacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyBacktestRequest) ProtoMessage() {}

func (x *StrategyBacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backtest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyBacktestRequest.ProtoReflect.Descriptor instead.
func (*StrategyBacktestRequest) Descriptor() ([]byte, []int) {
	return file_backtest_proto_rawDescGZIP(), []int{2}
}

func (x *StrategyBacktestRequest) GetDays() int64 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *StrategyBacktestRequest) GetTopN() int64 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *StrategyBacktestRequest) GetStrategyCode() uint64 {
	if x != nil {
		return x.StrategyCode
	}
	return 0
}

var File_backtest_proto protoreflect.FileDescriptor

const file_backtest_proto_rawDesc = "" +
	"\n" +
	"\x0ebacktest.proto\x12\bbacktest\"\x95\x01\n" +
	"\x0fBacktestRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x03R\x04days\x12\x12\n" +
	"\x04topN\x18\x02 \x01(\x03R\x04topN\x12\"\n" +
	"\fstrategyCode\x18\x03 \x01(\x04R\fstrategyCode\x12\"\n" +
	"\fsecurityCode\x18\x04 \x01(\tR\fsecurityCode\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\"\x7f\n" +
	"!SingleSecurityCodeBacktestRequest\x12\"\n" +
	"\fstrategyCode\x18\x01 \x01(\x04R\fstrategyCode\x12\"\n" +
	"\fsecurityCode\x18\x02 \x01(\tR\fsecurityCode\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"e\n" +
	"\x17StrategyBacktestRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x03R\x04days\x12\x12\n" +
	"\x04topN\x18\x02 \x01(\x03R\x04topN\x12\"\n" +
	"\fstrategyCode\x18\x03 \x01(\x04R\fstrategyCodeB\vZ\t/backtestb\x06proto3"

var (
	file_backtest_proto_rawDescOnce sync.Once
	file_backtest_proto_rawDescData []byte
)

func file_backtest_proto_rawDescGZIP() []byte {
	file_backtest_proto_rawDescOnce.Do(func() {
		file_backtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backtest_proto_rawDesc), len(file_backtest_proto_rawDesc)))
	})
	return file_backtest_proto_rawDescData
}

var file_backtest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_backtest_proto_goTypes = []any{
	(*BacktestRequest)(nil),                   // 0: backtest.BacktestRequest
	(*SingleSecurityCodeBacktestRequest)(nil), // 1: backtest.SingleSecurityCodeBacktestRequest
	(*StrategyBacktestRequest)(nil),           // 2: backtest.StrategyBacktestRequest
}
var file_backtest_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backtest_proto_init() }
func file_backtest_proto_init() {
	if File_backtest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backtest_proto_rawDesc), len(file_backtest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backtest_proto_goTypes,
		DependencyIndexes: file_backtest_proto_depIdxs,
		MessageInfos:      file_backtest_proto_msgTypes,
	}.Build()
	File_backtest_proto = out.File
	file_backtest_proto_goTypes = nil
	file_backtest_proto_depIdxs = nil
}
