// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_DATA_TYPE_ALL     DataType = 0 // 全部数据
	DataType_DATA_TYPE_BASE    DataType = 1 // 基础数据（如原始行情、基本面数据等）
	DataType_DATA_TYPE_FEATURE DataType = 2 // 特征数据（如衍生指标、计算特征等）
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_ALL",
		1: "DATA_TYPE_BASE",
		2: "DATA_TYPE_FEATURE",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_ALL":     0,
		"DATA_TYPE_BASE":    1,
		"DATA_TYPE_FEATURE": 2,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_data_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

// 回补数据
type RepairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=data.DataType" json:"data_type,omitempty"` // 数据类型， 全部数据，基础数据，特征数据
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                  // 开始日期
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                        // 结束日期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairRequest) Reset() {
	*x = RepairRequest{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairRequest) ProtoMessage() {}

func (x *RepairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairRequest.ProtoReflect.Descriptor instead.
func (*RepairRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *RepairRequest) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DATA_TYPE_ALL
}

func (x *RepairRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *RepairRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type UpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsFullUpdate     bool                   `protobuf:"varint,1,opt,name=is_full_update,json=isFullUpdate,proto3" json:"is_full_update,omitempty"`
	BaseDataKeyWords []string               `protobuf:"bytes,2,rep,name=base_data_key_words,json=baseDataKeyWords,proto3" json:"base_data_key_words,omitempty"`
	FeaturesKeyWords []string               `protobuf:"bytes,3,rep,name=features_key_words,json=featuresKeyWords,proto3" json:"features_key_words,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRequest) GetIsFullUpdate() bool {
	if x != nil {
		return x.IsFullUpdate
	}
	return false
}

func (x *UpdateRequest) GetBaseDataKeyWords() []string {
	if x != nil {
		return x.BaseDataKeyWords
	}
	return nil
}

func (x *UpdateRequest) GetFeaturesKeyWords() []string {
	if x != nil {
		return x.FeaturesKeyWords
	}
	return nil
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\x12\x04data\"v\n" +
	"\rRepairRequest\x12+\n" +
	"\tdata_type\x18\x01 \x01(\x0e2\x0e.data.DataTypeR\bdataType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\x92\x01\n" +
	"\rUpdateRequest\x12$\n" +
	"\x0eis_full_update\x18\x01 \x01(\bR\fisFullUpdate\x12-\n" +
	"\x13base_data_key_words\x18\x02 \x03(\tR\x10baseDataKeyWords\x12,\n" +
	"\x12features_key_words\x18\x03 \x03(\tR\x10featuresKeyWords*H\n" +
	"\bDataType\x12\x11\n" +
	"\rDATA_TYPE_ALL\x10\x00\x12\x12\n" +
	"\x0eDATA_TYPE_BASE\x10\x01\x12\x15\n" +
	"\x11DATA_TYPE_FEATURE\x10\x02B\aZ\x05/datab\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_proto_goTypes = []any{
	(DataType)(0),         // 0: data.DataType
	(*RepairRequest)(nil), // 1: data.RepairRequest
	(*UpdateRequest)(nil), // 2: data.UpdateRequest
}
var file_data_proto_depIdxs = []int32{
	0, // 0: data.RepairRequest.data_type:type_name -> data.DataType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		EnumInfos:         file_data_proto_enumTypes,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
