// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	backtest "xquant/biz/router/backtest"
	tracker "xquant/biz/router/tracker"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	tracker.Register(r)

	backtest.Register(r)

}
